"""The swap seam. One interface, two impls: LocalBus (production/dev/runtime,
Supabase-backed in real life) and BandBus (hackathon, load-bearing). Student
data NEVER rides BandBus — see caseband-band-boundary."""
from __future__ import annotations
from typing import Protocol, Iterable

from ..models.messages import BandMessage


class CollaborationBus(Protocol):
    def create_room(self, room: str, participants: list[str]) -> str: ...
    def send(self, msg: BandMessage) -> None: ...
    def stream(self, agent_id: str) -> Iterable[BandMessage]:
        """Messages addressed to agent_id (@mention routing), in order."""
        ...
    def fetch_transcript(self, room: str) -> list[BandMessage]:
        """Full ordered log — what the backend reducer/conductor reads."""
        ...
    def add_participant(self, room: str, agent_id: str) -> None: ...
    def remove_participant(self, room: str, agent_id: str) -> None: ...
    def lookup_peers(self, capability: str) -> list[str]: ...
